export const WATCHLATER = "WATCHLATER";
export const WATCHED = "WATCHED";
export const DELETEWATCHLATER = "DELETEWATCHLATER";
export const DELETEWATCHED = "DELETEWATCHED";
export const CURRENTMOVIE = "CURRENTMOVIE";